set(_AMENT_PACKAGE_NAME "robot_serving_bot")
set(robot_serving_bot_VERSION "0.0.0")
set(robot_serving_bot_MAINTAINER "Ilia O. <iliao@makerspet.com>")
set(robot_serving_bot_BUILD_DEPENDS "urdf")
set(robot_serving_bot_BUILDTOOL_DEPENDS "ament_cmake")
set(robot_serving_bot_BUILD_EXPORT_DEPENDS "urdf")
set(robot_serving_bot_BUILDTOOL_EXPORT_DEPENDS )
set(robot_serving_bot_EXEC_DEPENDS "urdf")
set(robot_serving_bot_TEST_DEPENDS )
set(robot_serving_bot_GROUP_DEPENDS )
set(robot_serving_bot_MEMBER_OF_GROUPS )
set(robot_serving_bot_DEPRECATED "")
set(robot_serving_bot_EXPORT_TAGS)
list(APPEND robot_serving_bot_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND robot_serving_bot_EXPORT_TAGS "<gazebo_ros gazebo_model_path=\"sdf\"/>")
