set(_AMENT_PACKAGE_NAME "kaiaai_msgs")
set(kaiaai_msgs_VERSION "0.3.0")
set(kaiaai_msgs_MAINTAINER "Ilia O. <iliao@kaia.ai>")
set(kaiaai_msgs_BUILD_DEPENDS "rosidl_default_generators" "rclcpp" "builtin_interfaces" "diagnostic_msgs")
set(kaiaai_msgs_BUILDTOOL_DEPENDS "ament_cmake")
set(kaiaai_msgs_BUILD_EXPORT_DEPENDS "rclcpp" "builtin_interfaces" "diagnostic_msgs")
set(kaiaai_msgs_BUILDTOOL_EXPORT_DEPENDS )
set(kaiaai_msgs_EXEC_DEPENDS "rosidl_default_runtime" "rclcpp" "builtin_interfaces" "diagnostic_msgs")
set(kaiaai_msgs_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(kaiaai_msgs_GROUP_DEPENDS )
set(kaiaai_msgs_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(kaiaai_msgs_DEPRECATED "")
set(kaiaai_msgs_EXPORT_TAGS)
list(APPEND kaiaai_msgs_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
