set(_AMENT_PACKAGE_NAME "auto_mapper")
set(auto_mapper_VERSION "0.0.0")
set(auto_mapper_MAINTAINER "omar <omar.gamil.salem@gmail.com>")
set(auto_mapper_BUILD_DEPENDS "rclcpp" "rclcpp_lifecycle" "sensor_msgs" "geometry_msgs" "nav_msgs" "nav2_msgs" "rclcpp_action" "tf2" "tf2_ros" "nav2_costmap_2d" "nav2_map_server" "slam_toolbox" "visualization_msgs" "nav2_util" "std_msgs" "map_msgs" "angles" "tf2_geometry_msgs" "behaviortree_cpp_v3")
set(auto_mapper_BUILDTOOL_DEPENDS "ament_cmake")
set(auto_mapper_BUILD_EXPORT_DEPENDS "rclcpp" "rclcpp_lifecycle" "sensor_msgs" "geometry_msgs" "nav_msgs" "nav2_msgs" "rclcpp_action" "tf2" "tf2_ros" "nav2_costmap_2d" "nav2_map_server" "slam_toolbox" "visualization_msgs" "nav2_util" "std_msgs" "map_msgs" "angles" "tf2_geometry_msgs" "behaviortree_cpp_v3")
set(auto_mapper_BUILDTOOL_EXPORT_DEPENDS )
set(auto_mapper_EXEC_DEPENDS "controller_manager" "joint_state_broadcaster" "forward_command_controller" "diff_drive_controller" "joint_trajectory_controller" "ros2_controllers_test_nodes" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "rviz2" "xacro" "robot_localization" "rclcpp" "rclcpp_lifecycle" "sensor_msgs" "geometry_msgs" "nav_msgs" "nav2_msgs" "rclcpp_action" "tf2" "tf2_ros" "nav2_costmap_2d" "nav2_map_server" "slam_toolbox" "visualization_msgs" "nav2_util" "std_msgs" "map_msgs" "angles" "tf2_geometry_msgs" "behaviortree_cpp_v3")
set(auto_mapper_TEST_DEPENDS "ament_lint_auto" "ament_lint_common" "ament_cmake_gmock" "ros2_control_test_assets")
set(auto_mapper_GROUP_DEPENDS )
set(auto_mapper_MEMBER_OF_GROUPS )
set(auto_mapper_DEPRECATED "")
set(auto_mapper_EXPORT_TAGS)
list(APPEND auto_mapper_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
