set(_AMENT_PACKAGE_NAME "kaiaai_gazebo")
set(kaiaai_gazebo_VERSION "0.0.0")
set(kaiaai_gazebo_MAINTAINER "Ilia O. <iliao@kaia.ai>")
set(kaiaai_gazebo_BUILD_DEPENDS "gazebo_ros_pkgs" "geometry_msgs" "nav_msgs" "rclcpp" "sensor_msgs" "tf2")
set(kaiaai_gazebo_BUILDTOOL_DEPENDS "ament_cmake")
set(kaiaai_gazebo_BUILD_EXPORT_DEPENDS "gazebo_ros_pkgs" "geometry_msgs" "nav_msgs" "rclcpp" "sensor_msgs" "tf2")
set(kaiaai_gazebo_BUILDTOOL_EXPORT_DEPENDS )
set(kaiaai_gazebo_EXEC_DEPENDS "kaiaai" "gazebo_ros_pkgs" "geometry_msgs" "nav_msgs" "rclcpp" "sensor_msgs" "tf2")
set(kaiaai_gazebo_TEST_DEPENDS )
set(kaiaai_gazebo_GROUP_DEPENDS )
set(kaiaai_gazebo_MEMBER_OF_GROUPS )
set(kaiaai_gazebo_DEPRECATED "")
set(kaiaai_gazebo_EXPORT_TAGS)
list(APPEND kaiaai_gazebo_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND kaiaai_gazebo_EXPORT_TAGS "<gazebo_ros gazebo_model_path=\"models\"/>")
