set(_AMENT_PACKAGE_NAME "makerspet_loki")
set(makerspet_loki_VERSION "0.0.0")
set(makerspet_loki_MAINTAINER "Ilia O. <iliao@makerspet.com>")
set(makerspet_loki_BUILD_DEPENDS "urdf")
set(makerspet_loki_BUILDTOOL_DEPENDS "ament_cmake")
set(makerspet_loki_BUILD_EXPORT_DEPENDS "urdf")
set(makerspet_loki_BUILDTOOL_EXPORT_DEPENDS )
set(makerspet_loki_EXEC_DEPENDS "urdf")
set(makerspet_loki_TEST_DEPENDS )
set(makerspet_loki_GROUP_DEPENDS )
set(makerspet_loki_MEMBER_OF_GROUPS )
set(makerspet_loki_DEPRECATED "")
set(makerspet_loki_EXPORT_TAGS)
list(APPEND makerspet_loki_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
list(APPEND makerspet_loki_EXPORT_TAGS "<gazebo_ros gazebo_model_path=\"sdf\"/>")
