set(_AMENT_PACKAGE_NAME "kaiaai_bringup")
set(kaiaai_bringup_VERSION "0.0.0")
set(kaiaai_bringup_MAINTAINER "Ilia O. <iliao@kaia.ai>")
set(kaiaai_bringup_BUILD_DEPENDS )
set(kaiaai_bringup_BUILDTOOL_DEPENDS "ament_cmake")
set(kaiaai_bringup_BUILD_EXPORT_DEPENDS )
set(kaiaai_bringup_BUILDTOOL_EXPORT_DEPENDS )
set(kaiaai_bringup_EXEC_DEPENDS "robot_state_publisher" "rviz2" "makerspet_snoopy" "makerspet_loki" "kaiaai_teleop" "ros2launch" "kaiaai_telemetry" "kaiaai" "makerspet_mini" "ros2launch" "joint_state_publisher" "joint_state_publisher_gui" "robot_state_publisher" "xacro" "cartographer_ros" "nav2_bringup")
set(kaiaai_bringup_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(kaiaai_bringup_GROUP_DEPENDS )
set(kaiaai_bringup_MEMBER_OF_GROUPS )
set(kaiaai_bringup_DEPRECATED "")
set(kaiaai_bringup_EXPORT_TAGS)
list(APPEND kaiaai_bringup_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
